### ISSUE TITLE
Ideas for T2s

### ISSUE THREAD

**Issue by MrDuck557** [MrDuck557/MoarWaterUnits#1]
I currently don't have ideas for the T2s, which will be named Manta Ray and Riptide
Reply to this, and if I like your idea, I'll implement it

**Comment by Arthur-The-Ok** [comment]
Riptide: a fast ship, a bit waek, equiped with two salvos and an hail cannon with strong knockback and when an enemy gets too close it release a powerfull shockwave that damages and pushes teh enemy, like it got hit by a big tidal wave

**Comment by MrDuck557** [comment]
How strong is the riptide going to be? 2 graphite salvos and 1 graphite hail have 163 DPS.
Minke has 238 DPS.

And also, I don't know how to implement the shockwave, the closest thing I can think of is a ring of knockback bullets.

**Comment by Arthur-The-Ok** [comment]
What about 3 graphite salvos, 1 titanium fuse  and 1 graphite ripple?

Em dom, 21 de mar de 2021 11:43, MrDuck557 ***@***.***>
escreveu:

**Comment by MrDuck557** [comment]
you don't know how powerful a fuse is?
this is a T2

**Comment by Arthur-The-Ok** [comment]
Ok, no fuse. But how high is the dps with 3 graphite salvos and a graphite
ripple?

Em dom, 21 de mar de 2021 12:02, MrDuck557 ***@***.***>
escreveu:

**Comment by MrDuck557** [comment]
336 DPS

**Comment by MrDuck557** [comment]
I might slap 2 salvos on the riptide and buff them tho

**Comment by Arthur-The-Ok** [comment]
Please specify what you are going to buff

Em dom, 21 de mar de 2021 12:11, MrDuck557 ***@***.***>
escreveu:

**Comment by MrDuck557** [comment]
probably the damage per hit

**Comment by Arthur-The-Ok** [comment]
Now, the shockwave, can it be done? If no, i think i can think of another
thing that can make the Riptide special

Em dom, 21 de mar de 2021 12:22, MrDuck557 ***@***.***>
escreveu:

**Comment by MrDuck557** [comment]
Doubt it, unless you want a ring of bullets

**Comment by Arthur-The-Ok** [comment]
A ring of bullets is linda of perfect for the shockwave

Em dom, 21 de mar de 2021 12:35, MrDuck557 ***@***.***>
escreveu:

**Comment by MrDuck557** [comment]
I'll try to implement it

**Comment by Arthur-The-Ok** [comment]
It feels good trying to be useful

Em dom, 21 de mar de 2021 12:41, MrDuck557 ***@***.***>
escreveu:

**Comment by MrDuck557** [comment]
I'm actually going to use your idea for the manta ray, since riptide is supposed to be support

**Comment by Arthur-The-Ok** [comment]
Oh, the Riptide is a support? Well, what about making the Riptide an
"anti-pest"?

Em dom, 21 de mar de 2021 13:04, MrDuck557 ***@***.***>
escreveu:
