### ISSUE TITLE
Riptide suggestions

### ISSUE THREAD

**Issue by MrDuck557** [MrDuck557/MoarWaterUnits#2]
I now have ideas for the Manta Ray, I need ideas for Riptide now.
Has to be support in some way

**Comment by Arthur-The-Ok** [comment]
Can the repair point block be converted into a turret? If so, you have your support boat right there. And it has a wave turret to put out any nearby units or blocks on fire, a small shield and, maybe, two segments

**Comment by MrDuck557** [comment]
want idea from someone else

**Comment by Arthur-The-Ok** [comment]
Sorry, i just wanted to help

Em ter, 23 de mar de 2021 12:10, MrDuck557 ***@***.***>
escreveu:

**Comment by LordDennis18** [comment]
> I now have ideas for the Manta Ray, I need ideas for Riptide now.
> Has to be support in some way

I would like to try to add some ideas for the Riptide

While in radius, units that are closer to the Riptide would give them "blessing of the sea" which boost their damage and increase their health also add a medium range regeneration (i think 20 blocks is enough) and maybe a shield that has 1000 or 750 health

I want to suggest a new water unit but I don't know what is the main role of the two types of water unit.

**Comment by MrDuck557** [comment]
I would say that that would be an op T3.
(seahorse path is lower health for speed and dps, and current path is direct unit support)

**Comment by LordDennis18** [comment]
For a direct unit support it would ok to just have a regeneration and shield support that ranges to 15 to 18 blocks and deflects ammo but has a small chance deflecting it. A little bit higher health and also a little slower than the seahorse since it supports units. Also add a machine gun turret for the riptide that burns the enemy target.

**Comment by MrDuck557** [comment]
If I accept your idea, I'm going to keep the regen, but leave out the shield. Also, a fast (not machine gun) healing missile launcher that doesn't burn

**Comment by LordDennis18** [comment]
> If I accept your idea, I'm going to keep the regen, but leave out the shield. Also, a fast (not machine gun) healing missile launcher that doesn't burn

Yeah, that's way more balance. Thanks for accepting the idea btw.

**Comment by MrDuck557** [comment]
I'm going to implement it after I resprite the manta
